### ISSUE TITLE
How can I sort the table information from the server

### ISSUE THREAD

**Issue by ZahraAmiri1996** [reyesoft/ngx-jsonapi#55] opened 2018-03-27 10:47 UTC
Hi friends
How can I sort the table information from the server, for example, how can I sort the names of a table alphabetically by server?

**Comment by max-SS** [comment] 2018-03-27 13:16
Hi!! 
If I understand correctly, it depends on what you use on your front end, for example we are using material, which provides us with the matSort component to achieve data sorting. As an alternative you can also create a pipe orderBy similar to angularjs.

**Comment by ZahraAmiri1996** [comment] 2018-03-28 07:27
I mean I want use json api sort,that request sort to server and deliver sorted Items, see http://jsonapi.org/format/#fetching-sorting

**Comment by pablorsk** [comment] 2018-05-04 17:28
Duplicate of #54

**Closed by pablorsk** 2018-05-04 17:28 UTC
