### ISSUE TITLE
Observable errors on Angular 6.1.0

### ISSUE THREAD

**Issue by baxelson12** [reyesoft/ngx-jsonapi#103] opened 2018-08-16 17:26 UTC
With the update to rxjs, I am receiving errors using the npm installed package.
`...rxjs/Observable"' has no exported member 'Observable'`

`npm install rxjs-compat@6 --save` Fixes this for the time being, but locations need to be updated.  Not sure if this is an issue if installed through git.

Thanks,
Brad

**Comment by pablorsk** [comment] 2018-08-18 14:51
Then, the problem is with Angular 6.1.0 rigth? 

@maxi7587 can you test this situation?

**Comment by maxi7587** [comment] 2018-08-31 23:49
rxjs imports will be fixed in the next release. This wasn't changed in the current version of the library to mantain compatibility with Angular 5 users, as commented in #81.

Thanks for reporting! You'll can safely remove rxjs-compat from your package.json soon, in the next major release.

**Comment by pablorsk** [comment] 2018-09-13 19:01
2.0.0-rc.2 released!

Migration guide: https://github.com/reyesoft/ngx-jsonapi/blob/v2.0/docs/migration.md

**Closed by pablorsk** 2018-09-13 19:01 UTC
Labels: help wanted
